### ISSUE TITLE
drone unintentionally yaw

### ISSUE THREAD

**Issue by Benedixx** [NovoG93/sjtu-drone#1]
i try to take off the drone and wait for a moment, it looks like the drone yaw by itself. tried to deactivate the wind on gazebo but still yaw, what might seems the problem here?

**Comment by NovoG93** [comment]
That is because of the motion noise added in the plugin.
With a6e22bf there is now a drone.yaml where you can configure the motion noise: https://github.com/NovoG93/sjtu_drone/blob/ros2/sjtu_drone_bringup/config/drone.yaml#L54-L59
