### ISSUE TITLE
[Enhancement]: Joystick Support

### ISSUE THREAD

**Issue by winstxnhdw** [NovoG93/sjtu-drone#12]
Hey, I am thinking of contributing a PR for joystick support, but I'd like to discuss how we should go about it first.

Would you prefer if it was an entirely new launch file that would launch the teleop joystick node, or should we stick with the current launch file but we pass some sort of flag as an argument?

For example,

```console
ros2 launch sjtu_drone_bringup sjtu_drone_bringup.launch.py joystick
```

I haven't checked if the `launch` API allows you to pass arguments to the launch file, but I reckon it's likely possible.

**Comment by NovoG93** [comment]
> Hey, I am thinking of contributing a PR for joystick support, but I'd like to discuss how we should go about it first.
> 
> Would you prefer if it was an entirely new launch file that would launch the teleop joystick node, or should we stick with the current launch file but we pass some sort of flag as an argument?
> 
> For example,
> 
> ```
> ros2 launch sjtu_drone_bringup sjtu_drone_bringup.launch.py joystick
> ```
> 
> I haven't checked if the `launch` API allows you to pass arguments to the launch file, but I reckon it's likely possible.

Hi, that sounds awesome!
I would suggest that the best option would be to keep the current lauch file and add an argument with which it is possible to switch between keyboard (default) and the joystick.
Looking forward to your contribution!

**Comment by noraise** [comment]
Hi @NovoG93, are there still plans to follow up with this? It looks like @winstxnhdw's PR is ready.

**Comment by NovoG93** [comment]
> Hi @NovoG93, are there still plans to follow up with this? It looks like @winstxnhdw's PR is ready.

Hi, already merged.
Sadly I dont have Joystick to test though

**Comment by noraise** [comment]
Tested it! Works great!
