### ISSUE TITLE
"world" frame is missing

### ISSUE THREAD

**Issue by ofer-baroz** [NovoG93/sjtu-drone#4]
When I launch the program, using:

    ros2 launch sjtu_drone_bringup sjtu_drone_bringup.launch.py

everything is initiating and I manage to move the drone using its teleope window.

The problem is, the simulation doesn't have any reference frame, and the "higher" frame is the one located in the urdf.xacro file which is "base_link".

In previous simulations I used, both in ROS and ROS2, the Gazebo simulator used to have some reference frame to describe the robot's positioning according to it. Creating a new "world" frame in the URDF and using a static_tf_broadcaster is not an option here, since I want the drone to move.

How can I solve this problem?

**Comment by NovoG93** [comment]
You will need to add a world link to the .world file
